### ISSUE TITLE
Config settings

### ISSUE THREAD

**Issue by eebmagic** [octobanana/peaclock#6]
Is there a config file somewhere or do I have to put in each command to get it to look how I want each time I open a window?

**Comment by octobanana** [comment]
As of a few minutes ago, there is now support for a configuration file!

The default config locations are `~/.config/ob/peaclock/config` and `~/.ob/peaclock/config`. A custom path can also be passed overriding the default locations using the `--config` option. The config directory and file must be created by the user. If the directory is not present, the program continues as normal.

The file, `config`, is a plain text file that can contain any of the commands listed in the __Commands__ section of the `--help` output. Each command must be on its own line.

An example config file would look like the following:
```
set compact off
set char Π
set hour 24
set bold on
set binary on
set digital off
set active #98225b
set inactive #2c323c
```

**Comment by MrYakobo** [comment]
Great! The config file is great to have. `--help` should output information about the config file though.
While you're at it, write a man page. We all love them :smile:
