### ISSUE TITLE
Clock is too small

### ISSUE THREAD

**Issue by Drugantibus** [octobanana/peaclock#7]
The clock appears pretty small on my terminal. I'm not sure if this is intended behavior or not, still I'd like to know if there is a way to make it bigger other than changing my font size. [Here's](https://imgur.com/DIt9WXP) a screenshot of how it looks like, and my [neofetch](https://imgur.com/DswhGyI) for reference.

**Comment by octobanana** [comment]
Yeah, that's the intended behaviour. Since it just uses characters, the size is determined by the font size.

Perhaps in the future there could be some draw functions added to draw the binary dots and digits in different sizes using multiple characters, or by changing the background colour.

**Comment by Drugantibus** [comment]
I see. Thank you!
